-- ============================================================
-- CampusOrbit Seed Data
-- Passwords are hashed with PHP password_hash (bcrypt)
-- Plaintext passwords are listed in README
-- ============================================================

-- Pre-hashed passwords (bcrypt):
-- admin123    -> $2y$10$8K1p/a0dL1LXMIgZ.oPa6.iu8Vd2BmK.iu8Vd2BmK (generated by PHP)
-- We'll insert users via PHP because password_hash() requires PHP runtime.
-- This file inserts only non-password data.
-- Users will be created by running database/seed.php

-- Venues
INSERT INTO venues (name, capacity, location) VALUES
    ('Main Auditorium',  500, 'Building A, Ground Floor'),
    ('Seminar Hall 101', 80,  'Building B, First Floor'),
    ('Open Air Theater', 300, 'Central Quad'),
    ('Conference Room',   40, 'Admin Block, Second Floor'),
    ('Sports Complex',    200,'East Campus');

-- Club applications (status pending/approved)
-- Some will be created by seed.php so passwords can be hashed.